const { VITE_GOOGLE_MAPS_API_KEY, VITE_GEOAPIFY_API_KEY, VITE_GOOGLE_PLACES_API_KEY} = import.meta.env 

export default {
    API_KEY: VITE_GOOGLE_MAPS_API_KEY,
    GEO_KEY: VITE_GEOAPIFY_API_KEY, 
    PLACE_KEY: VITE_GOOGLE_PLACES_API_KEY
}